export type Project={id:string;cat:string;name:string;desc:string;flow:string[];problem:string;solution:string;impact:string;stack:string[];link?:string;price?:string;image?:string};
export const services=[
{t:'AI Automation',d:'Designing n8n workflows and AI agents that connect APIs, webhooks, databases and business tools.',tags:['n8n','AI Agents','APIs','Webhooks']},
{t:'Real Estate Systems',d:'Lead capture, qualification, property enquiries and follow-up systems for property businesses.',tags:['Lead Generation','CRM','Follow-up','AI']},
{t:'Web Experiences',d:'Responsive websites and interfaces built around clarity, trust and conversion.',tags:['Next.js','HTML','CSS','WordPress']},
{t:'UI / UX Design',d:'Interfaces, user flows and prototypes that make digital products easier to understand and use.',tags:['Figma','UX Flows','Prototypes','Design']}];
export const projects:Project[]=[
{id:'01',cat:'AI AUTOMATION',name:'AI Lead Qualification',desc:'Captures, enriches and qualifies inbound leads before handing sales teams a clean next action.',flow:['Lead','AI','Qualification','CRM'],problem:'Sales teams lose time on unqualified enquiries while good leads wait for a reply.',solution:'A webhook receives each lead, an AI step scores intent and fit, rules route the result, and the CRM record is created with a suggested next action.',impact:'Designed to give sales a prioritised, ready-to-act list and shorten first response time.',stack:['n8n','AI Agents','Webhooks','CRM']},
{id:'02',cat:'REAL ESTATE',name:'Real Estate Lead System',desc:'Turns property enquiries into structured records with qualification and follow-up logic.',flow:['Property','Lead','Qualification','Follow-up'],problem:'Property enquiries arrive from many channels as unstructured messages, so follow-up is slow and inconsistent.',solution:'Enquiries are normalised into one record linked to the property, qualified on budget, timeline and intent, then queued for follow-up.',impact:'Designed to keep every enquiry traceable to a property and make follow-up consistent.',stack:['n8n','Supabase','APIs','AI']},
{id:'03',cat:'WORKFLOW',name:'Appointment Automation',desc:'An AI receptionist flow that collects details, checks availability and moves qualified requests toward booking.',flow:['Customer','AI Receptionist','Availability','Confirmation','Calendar'],problem:'Booking by back-and-forth messages is slow and staff are tied up answering repeat questions.',solution:'An AI receptionist gathers the details, checks open slots, proposes times and writes the confirmed booking to the calendar.',impact:'Designed to reduce manual scheduling and cut the messages needed to book.',stack:['n8n','AI Agents','Calendar API','Webhooks']},
{id:'04',cat:'VOICE AI',name:'AI Voice Sales Representative',desc:'A prototype architecture for outbound AI calls that introduce property offers, qualify prospects and request appointments.',flow:['Lead List','Voice AI','Qualify','Book Visit'],problem:'Calling prospect lists by hand is repetitive and hard to scale.',solution:'A prototype architecture where a voice agent calls prospects, introduces an offer, records answers and requests an appointment, passing results to the CRM.',impact:'Designed as a concept to explore how first-contact calls could be automated. It is a prototype architecture, not a deployed product.',stack:['Voice AI','APIs','Webhooks','CRM']},
{id:'05',cat:'WEB',name:'Business Website',desc:'A responsive business-facing web experience designed around clear services and conversion paths.',flow:['Visitor','Services','Proof','Enquiry'],problem:'Visitors leave when a business site does not explain what is offered or what to do next.',solution:'A clear page structure leads from services to trust signals to a single enquiry action, built responsive from the start.',impact:'Designed to make the offer understandable in seconds and the next step obvious.',stack:['Next.js','React','CSS','WordPress']},
{id:'06',cat:'UI / UX',name:'Automation Dashboard',desc:'A glassmorphism dashboard concept for monitoring leads, workflows and operational activity.',flow:['Events','Metrics','Workflows','Alerts'],problem:'Automations run out of sight, so teams cannot tell what is working or failing.',solution:'A dashboard concept that surfaces leads, workflow runs and failures in one glanceable interface.',impact:'Designed to make automation activity visible and problems quick to spot.',stack:['Figma','React','Supabase','UX Flows']},
{id:'07',cat:'AUTOMATION',name:'WhatsApp Lead Automation',desc:'A conversational workflow for capturing customer information and routing qualified conversations.',flow:['Message','Bot','Capture','Route'],problem:'Customers message on WhatsApp but details are scattered across chats.',solution:'A conversational flow asks the right questions, stores answers as a structured record and routes qualified chats to a person.',impact:'Designed to turn chat conversations into organised, actionable leads.',stack:['n8n','WhatsApp API','AI Agents','Webhooks']},
{id:'08',cat:'E-COMMERCE',name:'WooCommerce Store',desc:'A conversion-focused online store concept connected to automated order and customer workflows.',flow:['Browse','Checkout','Order','Customer Flow'],problem:'Small stores handle order updates and customer messages manually.',solution:'A store concept where each order triggers automated confirmation, status updates and follow-up.',impact:'Designed to reduce manual order handling and keep customers informed.',stack:['WooCommerce','WordPress','n8n','APIs']}];
export const tools=['n8n','AI Agents','APIs','Webhooks','Supabase','JavaScript','Next.js','React','WordPress','WooCommerce','Figma','GitHub'];
export const process=[['DISCOVER','Understand the business problem.'],['ARCHITECT','Map the data, tools and workflow.'],['BUILD','Connect the system and interface.'],['REFINE','Test, simplify and improve.']];

export type Service={t:string;d:string;tags:string[];price?:string;details?:string;image?:string};
export type Links={email:string;whatsapp:string;linkedin:string;github:string};
export type Content={services:Service[];projects:Project[];tools:string[];marquee:string[];heroTags:string[];links:Links;status:string};
const prices=['From $300','From $500','From $400','From $250'];
const details=['I design and build n8n workflows and AI agents around how your business already works. You describe the task you want to stop doing by hand, and I map it, connect your tools and test it before it goes live.','I set up systems that capture property enquiries, qualify the lead and trigger follow-up so no enquiry is missed. Built around your CRM or spreadsheet.','A responsive, fast website built around your services and one clear action for visitors. Built with Next.js or WordPress depending on what suits you.','User flows, interface designs and clickable prototypes in Figma, so you can see and test a product before it is built.'];
const detailed=services.map((s,i)=>({...s,price:prices[i],details:details[i]}));
const sample:Project={id:'09',cat:'SAMPLE',name:'Sample Project (edit me)',desc:'A placeholder project. Open Admin, then Projects, to edit or delete it.',flow:['Trigger','Data','AI','Result'],problem:'Describe the business problem this project solved.',solution:'Explain what you built and how the workflow runs, for example the n8n flow or AI agent.',impact:'Describe the intended benefit without inventing numbers.',stack:['n8n','AI Agents'],link:'',price:'Starting at $200'};
export const defaults:Content={links:{email:'hello@example.com',whatsapp:'2340000000000',linkedin:'https://www.linkedin.com/in/your-name',github:'https://github.com/your-username'},status:'Available for new projects',services:detailed,projects:[...projects,sample],tools,marquee:['AI AUTOMATION','AI AGENTS','N8N WORKFLOWS','REAL ESTATE','WEB DEVELOPMENT','UI / UX DESIGN','BUSINESS SYSTEMS'],heroTags:['AI AGENTS ↗','N8N WORKFLOWS','REAL ESTATE SYSTEMS']};
